In [1]:
import numpy as np

Numpy Indexing and Slicing Of Vectors

In [2]:
arr=np.arange(11,21)#Creating an array with elements from 11 to 20

Indexing

In [ ]:
arr[6] #Accessing the 7th element of the array (index starts from 0)
#Its called indexing. Indexing is used to access individual elements of an array. The index of the first element is 0, the index of the second element is 1, and so on. The index of the last element is n-1, where n is the number of elements in the array.

Slicing


In [3]:
arr[0:10] #Accessing elements from index 0 to 9 (10 is not included)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[4:]#Accessing elements from index 4 to the end of the array

array([15, 16, 17, 18, 19, 20])

In [5]:
arr[:5]#Accessing elements from index 0 to 4 (5 is not included)

array([11, 12, 13, 14, 15])

In [7]:
arr[3:10:2]#Accessing elements from index 3 to 9 (10 is not included) with a step of 2

array([14, 16, 18, 20])

Numpy Indexing and Slicing of Matrix


Indexing


In [21]:
arr=np.arange(1,31).reshape(6,5) #Creating a 2D array with 5 rows and 6 columns
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
arr[0] #Accessing the element of the first row 

array([1, 2, 3, 4, 5])

In [23]:
arr[0,0] #Accessing the element of the first row and first column

np.int64(1)

Slicing

In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
arr[0:2,1:4] #Accessing elements from the first and second row and columns 1 to 3 (4 is not included)

array([[2, 3, 4],
       [7, 8, 9]])

In [29]:
Slice=arr[3:6,3:5]
Slice                #Sliced portion can be stored in a variable. The sliced portion is a view of the original array, not a copy. This means that if we modify the sliced portion, the original array will also be modified.


array([[19, 20],
       [24, 25],
       [29, 30]])

BOOLEAN INDEXING

In [35]:
arr=np.arange(11,21) #creating an array with elements from 11 to 20
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
boolean_indexing=arr>15 
#Creating a boolean array where each element is True if the corresponding element in arr is greater than 15, and False otherwise
boolean_indexing

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
arr=arr[boolean_indexing]
 #Using the boolean array to index the original array, which returns a new array containing only the elements that are greater than 15
print(arr)

[16 17 18 19 20]


In [38]:
boolean_indexing=arr%2==0  
#Creating a boolean array where each element is True if the corresponding element in arr is even, and False otherwise
print(boolean_indexing)

[ True False  True False  True]


In [39]:
arr=arr[boolean_indexing] 
#Using the boolean array to index the original array, which returns a new array containing only the elements that are even
arr

array([16, 18, 20])