In [1]:
import numpy as np


Array Operation

Arithmatic operation


In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [3]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [4]:
a2-a1

array([5, 5, 5, 5, 5])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a2/a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [7]:
a1//a2  #floor division

array([0, 0, 0, 0, 0])

In [8]:
a1**a2


array([      1,     128,    6561,  262144, 9765625])

Broadcasting


In [74]:
l=[1,2,3,4,5]
arr=np.array(l)


In [75]:
arr+10 #you can't perform addition of a list and an integer directly, but you can convert the list to a numpy array and then perform the addition.


array([11, 12, 13, 14, 15])

In [76]:
arr=arr+1
arr

array([2, 3, 4, 5, 6])

Deep And Shallow copy


In [53]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Shallow Copy


In [54]:
slice=a[0:10] #it create shallow copy of the original array, so any changes made to the slice will also affect the original array. This is because both the slice and the original array share the same memory location. If you want to create a new array that is independent of the original array, you can use the copy() method to create a deep copy of the slice.
slice

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
a    #on slicing a shallow copy is created, so if we change the slice it will not affect the original array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Deep Copy

In [58]:
a
b=a  #Create a new variable b and assign it the value of a. This creates a reference to the same array in memory, so changes made to b will affect a as well.

In [59]:
b[0]=100
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [61]:
a  #changes made to b will also affect a, since they are both referencing the same array in memory.

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [63]:
#for creating shaLLOW COPY OF A USE copy() method
c=a.copy()
c[0]=1000
c

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [64]:
a  #changes made to c will not affect a, since c is a separate copy of the array in memory.

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])


MAtrix Operation 


In [107]:
a=np.array([[1,2,3],[4,5,6]])
b=np.arange(1,10).reshape(3,3)
c=np.arange(1,22).reshape(3,7)

MUltiplication


In [ ]:
#The alignment condition for matrix multiplication requires that the number of columns in the first matrix must equal the number of rows in the second matrix
#ignoring the alignment condition for matrix multiplication can lead to errors or unexpected results. It is important to ensure that the matrices being multiplied are compatible in terms of their dimensions.

In [97]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
a @ b #matrix multiplication

array([[30, 36, 42],
       [66, 81, 96]])

In [108]:
np.dot(a,c) #matrix multiplication using dot function

array([[ 62,  68,  74,  80,  86,  92,  98],
       [134, 149, 164, 179, 194, 209, 224]])

Transpose


In [ ]:
#in Transpose of a matrix, the rows become columns and the columns become rows. This operation is denoted by the symbol T. 
# The transpose of a matrix is useful in many applications, such as solving systems of linear equations and finding eigenvalues and eigenvectors.

In [109]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
a.T  #transpose of a matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

Advance Array Manipulation

Stacking array


In [ ]:
#Two Matrix can't be stacked if they have different number of columns. The number of columns in both matrices must be the same for them to be stacked vertically. If the number of columns is different, it will result in a ValueError.

In [115]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [113]:
np.vstack((a,b))  #vertical stacking of two arrays

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
np.hstack((a,b))  #horizontal stacking of two arrays

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
np.column_stack((a,b))  #column stacking of two arrays

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splitting Array 



In [121]:
d=np.arange(16).reshape(4,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
np.hsplit(d,2)  #split the array into 2 equal parts horizontally

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [123]:
np.hsplit(d,4)  #split the array into 4 equal parts horizontally

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [128]:
np.vsplit(d,2)  #split the array into 2 equal parts vertically

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [129]:
z=np.vsplit(d,4)  #split the array into 4 equal parts vertically  

In [ ]:
for i in z:    #may be z have splited array but it is stored in form of matrix so we have to iterate over it to get the individual array
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
