importing NumPy

In [3]:
import numpy as np

Basic Array Creation

In [8]:
arr=np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [1]:
a=[1, 2, 3, 4, 5,"hellow"]
a

[1, 2, 3, 4, 5, 'hellow']

In [4]:
np.array(a)

array(['1', '2', '3', '4', '5', 'hellow'], dtype='<U21')

In [5]:
b=[[1, 2, 3], [4, 5, 6]]
b

[[1, 2, 3], [4, 5, 6]]

In [7]:
np.array(b)



array([[1, 2, 3],
       [4, 5, 6]])

Array generation function


In [8]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr=np.zeros(3) #for 1D array
arr1=np.zeros((3,4)) #for 2D array  (rows,columns)
print(arr)
print(arr1) 


[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
arr=np.ones(3) #for 1D array
arr1=np.ones((3,4)) #for 2D array  (rows,   columns)
print(arr)
print(arr1)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr=np.linspace(1,10,5) #start,stop,number of elements
arr#elements are equally spaced between start and stop

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Random Generation function


In [ ]:
np.random.rand(5) #random numbers between 0 and 1     #Normalization of data is done using this function

array([0.56730089, 0.87813381, 0.6357974 , 0.89302591, 0.54831933])

In [ ]:
np.random.randn(5) #random numbers from standard normal distribution  #standard normal distribution has mean=0 and std=1

array([ 0.84746885, -0.00790966,  0.62938624,  1.7555677 , -1.27975794])

In [ ]:
np.random.randint(10,20,11) #random integers between 10 and 20 (20 is exclusive) and 11 is the number of elements

array([16, 14, 18, 15, 10, 19, 15, 15, 11, 19, 14], dtype=int32)

Array Attribute


In [21]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
arr.shape

(2, 3)

In [23]:
arr.size

6

In [24]:
arr.dtype

dtype('int64')

Array Meathod

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.max()

np.int64(6)

In [27]:
arr.sum()

np.int64(21)

In [28]:
arr.sum(axis=0) #sum of each column


array([5, 7, 9])

In [29]:
arr.sum(axis=1) #sum of each row

array([ 6, 15])

In [30]:
arr.mean() #mean of all elements

np.float64(3.5)

In [ ]:
arr.std() #standard deviation of all elements

In [31]:
arr.argmax() #index of maximum element

np.int64(5)

In [ ]:
arr.argmin() #index of minimum element


Reshape and Resize


In [34]:
arr=np.arange(1,11)

In [36]:
arr.reshape(5,2) #reshape the array to 5 rows and 2 columns

#Remember no of elements should be same in original and reshaped array
#tere for select the number of rows and columns such that their product is equal to the number of elements in the original array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
arr=arr.reshape(5,2) #Assigning the reshaped array to original array is called resizing the array. Now arr is a 2D array with 5 rows and 2 columns